# Basic Site Information
site_name: QSpace Documentation
nav:
  - Getting started:
    - What is QSpace?: index.md
    - Community Edition: community.md
    - Installation:
      - "Install on Linux": installation/Linux.md
      - "Install on macOS": installation/macOS.md
      - "Troubleshooting": installation/troublesh.md
      - "Customization": installation/customize.md
    - Development:
      - "Changelog": changelog.md
  - Tutorial:
    - "Get to Know QSpace": tutorial/Get2Know.md
    - "Clebsch-Gordan Coefficients": tutorial/CGCoeff.md
    - "Generate Local Operators": tutorial/LocalOps.md
    - "Understand QSpace Objects": tutorial/QSpaceObj.md
    - "Access QSpace Data": tutorial/QSpaceData.md
    - Operations:
      - "Basic Operations": tutorial/BasicOps.md
      - "Access Subspaces": tutorial/Subspace.md
      - "Contraction": tutorial/Contraction.md
      - "Direct Sum": tutorial/DrctSum.md
      - "Eigen-decomposition": tutorial/EigenDecomp.md
      - "Singular Value Decomposition": tutorial/SingValDecomp.md
    - Special Case:
      - "Rank-2 Tensors": tutorial/Rank2.md
      - "Vacuum Space": tutorial/Vacuum.md
      - "Identity & Isometry": tutorial/Isometries.md
    - Technicality:
      - "Truncation of Zeros": tutorial/ZeroTrunc.md
      - "Normalization Convention": tutorial/NormConv.md
      - "Outer Multiplicity": tutorial/OuterMult.md

    # - "Starting Point: getLocalSpace": tutorial/getLocalSpace.md
  - Examples:
    # - Iterative Diagonalization: iterdiag.md
    - NRG Examples: 
      # - "Spin-1/2 1-Channel Kondo": examples/NRG/Ex_1CK.md
      # - "Spinless 2-Channel Impurity": examples/NRG/Ex_NonDiag.md
      # - "NRG for SIAM": examples/NRG/Ex_SIAM.md
      # - "iNRG for SIAM": examples/NRG/Ex_SIAM_iNRG.md
      # - "NRG Energy Flow": examples/NRG/NRG_Eflow.md
      - "NRG-1: Energy Flow": examples/NRG/NRG1_Energy_Flow.md
      - "NRG-2: Impurity Contribution  to Thermaldynamic  Properties": examples/NRG/NRG2_ImpThermo.md
      - "NRG-3: Impurity Spectral Function": examples/NRG/NRG3_ImpSpec.md
      - "NRG for SIKM": examples/NRG/NRG_Kondo.md
      - "SIKM Thermal Properties": examples/NRG/NRG_Kondo_Thermal.md
      - "NRG for Spectral Functions": examples/NRG/NRG_SpecFunc.md
    - DMRG Examples:
      - "2D Hubbard Model": examples/DMRG/DMRGHubbard2D.md
  - Reference:
    - compactQS: reference/compactQS.md
    - contractQS: reference/contractQS.md
    - diagQS: reference/diagQS.md
    - eigQS: reference/eigQS.md
    - fdmNRG_QS: reference/fdmNRG_QS.md
    - fgrNRG: reference/fgrNRG.md
    - getDimQS: reference/getDimQS.md
    - getIdentityQS: reference/getIdentityQS.md
    - getLocalSpace: reference/getLocalSpace.md
    - getQDimQS: reference/getQDimQS.md
    - getRC: reference/getRC.md
    - getSmoothSpec: reference/getSmoothSpec.md
    - getSmoothTDM: reference/getSmoothTDM.md
    - getSymStates: reference/getSymStates.md
    - isHConjQS: reference/isHConjQS.md
    - isIdentityCG: reference/isIdentityCG.md
    - isIdentityQS: reference/isIdentityQS.md
    - makeUniqueQS: reference/makeUniqueQS.md
    - normQS: reference/normQS.md
    - orthoQS: reference/orthoQS.md
    - permuteQS: reference/permuteQS.md
    - plusQS: reference/plusQS.md
    - setupRCStore: reference/setupRCStore.md
    - skipZerosQS: reference/skipZerosQS.md
    - svdQS: reference/svdQS.md
    - tdmNRG: reference/tdmNRG.md
    - traceQS: reference/traceQS.md

  - Contribute:
    - How to Contribute: contribg.md
    - Markdown Guide: mdref.md
    - MkDocs Guide: mkdocsg.md

# DO NOT TOUCH BELOW THIS LINE !!!
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.code.copy
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

# Repository
repo_name: QSpace Documentation
repo_url: https://github.com/Open-Source-QSpace/QSpace-Documentation
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 Open Source QSpace Organization

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      exclude:
        - index.md
  - git-committers:
      repository: Open-Source-QSpace/QSpace-Documentation
      branch: main
      exclude:
        - index.md

extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            raising issues in our <a href="https://github.com/Open-Source-QSpace/QSpace-Documentation/issues" target="_blank" rel="noopener">repository</a>.
  social:
    - icon: fontawesome/brands/github
      name: Organization
      link: https://github.com/Open-Source-QSpace
    - icon: fontawesome/brands/bitbucket
      name: QSpace4u
      link: https://bitbucket.org/qspace4u
    - icon: fontawesome/brands/x-twitter
      name: Technicality
      link: https://arxiv.org/abs/2405.06632
    - icon: fontawesome/brands/airbnb
      name: MATLAB
      link: https://www.mathworks.com/products/matlab.html

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/feedback.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
