# Basic Site Information
site_name: QSpace Documentation
nav:
  - Getting started:
    - What is QSpace?: index.md
    - Installation:
      - "Install on Linux": Linux.md
  - Tutorial:
    - "Get to Know QSpace": tutorial/QSpace_intro.md
    - "Starting Point: getLocalSpace": tutorial/getLocalSpace.md
    - "NRG-1: Energy Flow": tutorial/NRG1_Energy_Flow.md
    - "NRG-2: Impurity Contribution  to Thermaldynamic  Properties": tutorial/NRG2_ImpThermo.md
    - "NRG-3: Impurity Spectral Function": tutorial/NRG3_ImpSpec.md
  - Examples:
    - Iterative Diagonalization: iterdiag.md
    - NRG Examples: 
      # - "Spin-1/2 1-Channel Kondo": examples/NRG/Ex_1CK.md
      # - "Spinless 2-Channel Impurity": examples/NRG/Ex_NonDiag.md
      # - "NRG for SIAM": examples/NRG/Ex_SIAM.md
      # - "iNRG for SIAM": examples/NRG/Ex_SIAM_iNRG.md
      - "NRG Energy Flow": examples/NRG/NRG_Eflow.md
      - "NRG for SIKM": examples/NRG/NRG_Kondo.md
      - "SIKM Thermal Properties": examples/NRG/NRG_Kondo_Thermal.md
      - "NRG for Spectral Functions": examples/NRG/NRG_SpecFunc.md
    - DMRG Examples:
      - "2D Hubbard Model": examples/DMRG/DMRGHubbard2D.md
  - Reference:
    - getLocalSpace: reference/getLocalSpace.md
    - contractQS: reference/contractQS.md
  - Contribute:
    - How to Contribute: contribg.md
    - Markdown Guide: mdref.md
    - MkDocs Guide: mkdocsg.md

# DO NOT TOUCH BELOW THIS LINE !!!
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - content.action.edit
    - content.action.view
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

# Repository
repo_name: QSpace Documentation
repo_url: https://github.com/Open-Source-QSpace/QSpace-Documentation
edit_uri: edit/main/docs/

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
